//snackbar
const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR'
const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR'
const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR'
//file upload
const FILE_UPLOAD = 'FILE_UPLOAD'
const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS'
const FILE_UPLOAD_FAIL = 'FILE_UPLOAD_FAIL'
//updat grid
const UPDATE_GRID = 'UPDATE_GRID'

export default {
  FILE_UPLOAD,
  FILE_UPLOAD_SUCCESS,
  FILE_UPLOAD_FAIL,
  ENQUEUE_SNACKBAR,
  CLOSE_SNACKBAR,
  REMOVE_SNACKBAR,
  UPDATE_GRID,
}
